name: Success Check Action

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print Success Message
        run: echo "Build Successful!! Push was successful"